# Sample
#
#filerepository:
#  privateToken: your_secret_gitlab_token
#
#filegroups:
#  groups:
#    - name: localFilesSample
#      fileLocations:
#        - /path/to/sample1.properties
#        - /path/to/sample2.properties
#    - name: removeFilesSample
#      fileLocations:
#        - http://url.to.file/sample1.properties
#        - http://url.to.file/sample2.properties