filegroups:
  groups:
    - name: cms-valid-1-psw1
      filePaths:
        - /Users/leomillon/repos/ekino/apps/frontoffice/src/main/resources/config/common/common.properties
        - /Users/leomillon/repos/ekino/apps/frontoffice/src/main/resources/config/common/services.properties
        - /Users/leomillon/repos/ekino/apps/frontoffice/src/main/resources/config/users/ezy-sc.properties
        - /Users/leomillon/repos/ekino/apps/frontoffice/src/main/resources/config/users/cms-valid-1-psw1.properties